### ISSUE TITLE
Where's the default rank image stored?

### ISSUE THREAD

**Issue by N1lzh** [neplexlabs/canvacord#131]
Hi, I was wondering where the default rank image - so that on which the rank, the level, the xp etc are added - is stored. I couldn't find it anywhere in the `node_moduels/canvacord` folder. Nevertheless the library is great, I really enjoy working with it!

**Comment by DevAndromeda** [comment]
@N1lzh it is stored in-memory, or a state of that particular card builder class instance. A `Rank` instance is by default initialized with some fixed variables which is defined here: https://github.com/DevAndromeda/canvacord/blob/755f52159402071ec6745a4702e3ab1bf3a2f49c/src/Rank.js#L90-L160
